defaults:
  - datamodule: pcs
  - model: default
  - trainer: default

model:
  model_instance:
    _target_: segmentator.models.unet.get_unet
    backbone_name: convnext_tiny

datamodule:
  batch_size: 12




