_target_: lightning.pytorch.Trainer
accelerator: gpu
devices: 1
max_epochs: 100
callbacks:
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 3
    verbose: True
    mode: min
  - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: epoch
precision: 16